name: MiCard
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  
  fonts:
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
  
    - family: RockSalt
      fonts:
        - asset: fonts/RockSalt-Regular.ttf
  
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf